# coding: utf-8
from filesystem import paths
from filesystem.paths import ROOT

APP = ROOT + paths.APP
APP_HTTP = ROOT + paths.APP_HTTP
APP_PROVIDERS = ROOT + paths.APP_PROVIDERS
APP_HTTP_CONTROLLERS = ROOT + paths.APP_HTTP_CONTROLLERS
APP_HTTP_MIDDLEWARE = ROOT + paths.APP_HTTP_MIDDLEWARE
BOOTSTRAP = ROOT + paths.BOOTSTRAP
BOOTSTRAP_CACHE = ROOT + paths.BOOTSTRAP_CACHE
CONFIG = ROOT + paths.CONFIG
DATABASES = ROOT + paths.DATABASES
DATABASES_MIGRATIONS = ROOT + paths.DATABASES_MIGRATIONS
RESOURCES = ROOT + paths.RESOURCES
RESOURCES_TEMPLATES = ROOT + paths.RESOURCES_TEMPLATES
RESOURCES_SNIPPETS = ROOT + paths.RESOURCES_SNIPPETS
ROUTES = ROOT + paths.ROUTES
STORAGE = ROOT + paths.STORAGE
STORAGE_COMPILED = ROOT + paths.STORAGE_COMPILED
STORAGE_STATIC = ROOT + paths.STORAGE_STATIC
STORAGE_UPLOADS = ROOT + paths.STORAGE_UPLOADS
TESTS = ROOT + paths.TESTS
