# coding: utf-8
from filesystem import Paths
from filesystem.Paths import ROOT

APP = ROOT + Paths.APP
APP_HTTP = ROOT + Paths.APP_HTTP
APP_PROVIDERS = ROOT + Paths.APP_PROVIDERS
APP_HTTP_CONTROLLERS = ROOT + Paths.APP_HTTP_CONTROLLERS
APP_HTTP_MIDDLEWARE = ROOT + Paths.APP_HTTP_MIDDLEWARE
BOOTSTRAP = ROOT + Paths.BOOTSTRAP
BOOTSTRAP_CACHE = ROOT + Paths.BOOTSTRAP_CACHE
CONFIG = ROOT + Paths.CONFIG
DATABASES = ROOT + Paths.DATABASES
DATABASES_MIGRATIONS = ROOT + Paths.DATABASES_MIGRATIONS
RESOURCES = ROOT + Paths.RESOURCES
RESOURCES_TEMPLATES = ROOT + Paths.RESOURCES_TEMPLATES
ROUTES = ROOT + Paths.ROUTES
STORAGE = ROOT + Paths.STORAGE
STORAGE_COMPILED = ROOT + Paths.STORAGE_COMPILED
STORAGE_STATIC = ROOT + Paths.STORAGE_STATIC
STORAGE_UPLOADS = ROOT + Paths.STORAGE_UPLOADS
TESTS = ROOT + Paths.TESTS
